### PR TITLE
added my name in contributer

### PR DESCRIPTION
**Pull request by Ashana700**
Fixes # .

Changes proposed in this pull request:
- change in contributor name in doc/general/introduction.rst

@pgRouting/admins

### CODE REVIEW

**Comment by dkastl** [comment]
What did you contribute to the project to add your name to the list of contributors?

**Comment by krashish8** [comment]
Well, this PR is a part of GSoC pgRouting application requirements - [Task 2: Experience with GitHub & Git](https://github.com/pgRouting/pgrouting/wiki/GSoC-Ideas%3A-2022#task-2-experience-with-github--git) (Vicky added this task last year).

The PR description could have been made more clear. Of course, this is the GSoC-pgRouting repository and not the main pgRouting, so the pull request won't be honored, it is just for testing skills using Git/GitHub ;-)

**Comment by dkastl** [comment]
Ah, now I see the list point. Thanks for the link!

I saw that this was for the GSoC repository. Maybe we can make another example commit? But I must say that I don't have a good example right now.

**Comment by cvvergara** [comment]
probably you need to read the documentation, because the placement of the name is not where it is supposed to be.

**Comment by Ashana700** [comment]
Closing this PR, opened a new PR# , which does the same changes at the right place. 
Sorry, I got confused and instead of checking out from develop, I checked out from vrprouting-develop.
Apologies and Thanks.

**Pull request closed without merging**
