### PR TITLE
GSoC 22 Manas Sivakumar : Week 4

### PR DESCRIPTION
**Pull request by Manas23601**
Fixes # .

Changes proposed in this pull request:
-
-
-

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
Change the title of your PR

**Comment by cvvergara** [comment]
Lets keep the focus on the actions
instead of:
```
on:
  push:
    branches-ignore:
      - 'translations_*'
    tags: []
  pull_request:
    paths-ignore:
      - '**.po'
```
Use:
```
on:
  workflow_dispatch:
```
do that on all the ./github/worflow/*.yml
except on these 2 files:
ubuntu.yml, check-files.yml

**Comment by Manas23601** [comment]
The procedure to add google-or tools is not clear to me.
I explored two approaches : 
1. Use the ### find_package function:

**Comment by Manas23601** [comment]
for adding ortools to cmake I downloaded the source code from github and built it using cmake. The workflow in ubuntu.yml is different,. I'm not downloading the binary version as a .tar.gz and extracting it

**Pull request merged**
