### PR TITLE
GSoC 22 : Manas Sivakumar Week 6

### PR DESCRIPTION
**Pull request by Manas23601**
Fixes # .

Changes proposed in this pull request:
-
-
-

@pgRouting/admins

### CODE REVIEW

**Comment by Manas23601** [comment]
OR tools example : https://github.com/Manas23601/google-or-practise.

**Comment by Manas23601** [comment]
I tried asking for help in OR Tools official discord channel. I did whatever I could understand.   

so far I'm able to access the ortools library inside the repository. its failing when I use an actual function. I will attach the output log below.   

I don't know why its happening.

**Comment by Manas23601** [comment]
Please take a look at the discord conversation as well. ("general" room). To summarise OR tools when installed from source and built works with a `make run SOURCE=\path\to\file.cc` but not with `g++ -std=c++17 file.cc`

**Comment by cvvergara** [comment]
something like
```
git mv  * test_or_tools
```

**Comment by cvvergara** [comment]
Instruction to "install google-or-tools in your local machine"

**Comment by Manas23601** [comment]
git clone git@github.com:google/or-tools.git
cmake -S. -Bbuild -DBUILD_DEPS:BOOL=ON
cmake --build build

**Pull request merged**
